### ISSUE TITLE
free5gc amf v3.0.2 is crashed on receipt the PDU Session Establishment Request which is encoded by gnbsim.

### ISSUE THREAD

**Issue by hhorai** [hhorai/gnbsim#3]
AMF (free5gc v3.0.2 is crashed on receipt my pdu.
I think that the problem is in my PDU session establishement encoder.
Here are the output messages.

> amf              | TRAC[2020-06-17T14:59:27Z]/go/src/free5gc/src/amf/ngap/handler.go:234 free5gc/src/amf/ngap.HandleUplinkNasTransport() RANUENGAPID[0] AMFUENGAPID[1]                 AMF=NGAP
> amf              | WARN[2020-06-17T14:59:27Z]/go/src/free5gc/src/amf/nas/nas_security/security.go:174 free5gc/src/amf/nas/nas_security.Decode() NAS MAC verification failed(0xb77375ff != 0x01c1ffff)  AMF=NAS
> amf              | panic: runtime error: index out of range
> amf              | 
> amf              | goroutine 7 [running]:
> amf              | free5gc/lib/nas.GetEPD(...)
> amf              | 	/go/src/free5gc/lib/nas/nas.go:100
> amf              | free5gc/lib/nas.(*Message).PlainNasDecode(0xc000bb5800, 0xc0008e32f0, 0xe80326, 0x29)
> amf              | 	/go/src/free5gc/lib/nas/nas.go:172 +0x17e
> amf              | free5gc/src/amf/nas/nas_security.Decode(0xc000832b00, 0x1, 0xc000bb78b7, 0x0, 0x1, 0x0, 0x0, 0x0)
> amf              | 	/go/src/free5gc/src/amf/nas/nas_security/security.go:189 +0x1f3
> amf              | free5gc/src/amf/nas.HandleNAS(0xc000810fc0, 0x2e, 0xc000bb78b0, 0x7, 0x8)
> amf              | 	/go/src/free5gc/src/amf/nas/handler.go:26 +0xb3
> amf              | free5gc/src/amf/ngap.HandleUplinkNasTransport(0xc0007c6460, 0xc000bb4620)
> amf              | 	/go/src/free5gc/src/amf/ngap/handler.go:240 +0x73b
> amf              | free5gc/src/amf/ngap.Dispatch(0xc0008868e0, 0x11, 0xc000b9a000, 0x32, 0x2000)
> amf              | 	/go/src/free5gc/src/amf/ngap/dispatcher.go:41 +0x4f2
> amf              | free5gc/src/amf/handler.Handle()
> amf              | 	/go/src/free5gc/src/amf/handler/handler.go:36 +0x1ec
> amf              | created by free5gc/src/amf/service.(*AMF).Start
> amf              | 	/go/src/free5gc/src/amf/service/amf_init.go:145 +0x4a9`

**Comment by hhorai** [comment]
Now free5gc amf works well.
But its log message tells us "WARN[2020-06-18T16:33:48Z]/go/src/free5gc/src/amf/nas/dispatch.go:21 free5gc/src/amf/nas.Dispatch() GSM Message should include in GMM Message     AMF=NAS".
I will try to read the code of free5gc.

**Comment by hhorai** [comment]
I have fixed this issue. But I have recognized another problem...
