### ISSUE TITLE
Segmentation fault while running example in gNb simulator for free5gc

### ISSUE THREAD

**Issue by namachis** [hhorai/gnbsim#32]
I have got segmentation fault while running the example given in gNb simulator by following the steps by providing amf ip to the example. The free5gc version is 3.0.4.  All the components of Free5GC are running in docker containers. I have attached the logs from amf and gnb sim. 

I tried to execute the gnb simulator from the same VM where free5gc containers are running.

I am able to ping the ip of the amf.  Here are the logs from gNb simulator
ubuntu@free5g_304:~/gnbsim/example$ ping 10.100.200.12
PING 10.100.200.12 (10.100.200.12) 56(84) bytes of data.
64 bytes from 10.100.200.12: icmp_seq=1 ttl=64 time=0.154 ms
64 bytes from 10.100.200.12: icmp_seq=2 ttl=64 time=0.045 ms
64 bytes from 10.100.200.12: icmp_seq=3 ttl=64 time=0.046 ms

gNb simulator logs
---------------------

ubuntu@free5g_304:~/gnbsim/example$ ./example 10.100.200.12
[gnbsim]2021/01/01 11:26:39.343206 example.go:66: Dail LocalAddr: 127.0.0.1/192.168.122.12/172.17.0.1/172.16.219.64/192.168.123.1/10.100.200.1:38412; RemoteAddr: 127.0.0.1/192.168.122.12/172.17.0.1/172.16.219.64/192.168.123.1/10.100.200.1:38412
[gnbsim]2021/01/01 11:26:39.343250 example.go:71: SndBufSize: 212992, RcvBufSize: 212992
[gnbsim]2021/01/01 11:26:39.343318 example.go:90: write: len 44, info: &{Stream:0 SSN:0 Flags:0 _:0 PPID:1006632960 Context:0 TTL:0 TSN:0 CumTSN:0 AssocID:0}
[gnbsim]2021/01/01 11:26:39.343401 example.go:111: read: len 44, info: &{Stream:0 SSN:0 Flags:0 _:0 PPID:1006632960 Context:0 TTL:0 TSN:2316183121 CumTSN:0 AssocID:40}
dump: 00150028000003001b00080002f839000000040066001000000000010002f839000010080102030015400100
Procedure Code: id-NGSetup (21)
PDU Length: 40
Protocol IEs: 3 items
  Item 0
[gnbsim]2021/01/01 11:26:39.343424 ngap.go:640: Unsupported Protocol IE: 27
    Protocol IE:  (27)
      IE length: 8
        decoding id(27) not supported yet.
        dump: 0002f83900000004
  Item 1
[gnbsim]2021/01/01 11:26:39.343447 ngap.go:640: Unsupported Protocol IE: 102
    Protocol IE:  (102)
      IE length: 16
        decoding id(102) not supported yet.
        dump: 00000000010002f83900001008010203
  Item 2
[gnbsim]2021/01/01 11:26:39.343487 ngap.go:640: Unsupported Protocol IE: 21
    Protocol IE:  (21)
      IE length: 1
        decoding id(21) not supported yet.
        dump: 00
[gnbsim]2021/01/01 11:26:39.343569 example.go:90: write: len 75, info: &{Stream:0 SSN:0 Flags:0 _:0 PPID:1006632960 Context:0 TTL:0 TSN:2316183121 CumTSN:0 AssocID:40}
[gnbsim]2021/01/01 11:26:39.343607 example.go:111: read: len 75, info: &{Stream:0 SSN:1 Flags:0 _:0 PPID:1006632960 Context:0 TTL:0 TSN:2316183122 CumTSN:0 AssocID:40}
dump: 000f40470000050055000200000026001d1c7e004179000d0102f8392143000000000000301001202e0480a000000079000f4002f839000004001002f839000001005a4001180070400100
Procedure Code: id-InitialUEMessage (15)
PDU Length: 71
Protocol IEs: 5 items
  Item 0
    Protocol IE: id-RAN-UE-NGAP-ID (85)
      IE length: 2
        decoding id(85) not supported yet.
        dump: 0000
  Item 1
    Protocol IE: id-NAS-PDU (38)
      IE length: 29
        EPD: 5G Mobility Management (0x7e)
        Security Header: 0x0
        Message Type: Registration Request (0x41)
  Item 2
[gnbsim]2021/01/01 11:26:39.343656 ngap.go:640: Unsupported Protocol IE: 121
    Protocol IE:  (121)
      IE length: 15
        decoding id(121) not supported yet.
        dump: 4002f839000004001002f839000001
  Item 3
[gnbsim]2021/01/01 11:26:39.343670 ngap.go:640: Unsupported Protocol IE: 90
    Protocol IE:  (90)
      IE length: 1
        decoding id(90) not supported yet.
        dump: 18
  Item 4
[gnbsim]2021/01/01 11:26:39.343684 ngap.go:640: Unsupported Protocol IE: 112
    Protocol IE:  (112)
      IE length: 1
        decoding id(112) not supported yet.
        dump: 00
[gnbsim]2021/01/01 11:26:39.343737 example.go:90: write: len 62, info: &{Stream:0 SSN:1 Flags:0 _:0 PPID:1006632960 Context:0 TTL:0 TSN:2316183122 CumTSN:0 AssocID:40}
[gnbsim]2021/01/01 11:26:39.545966 example.go:111: read: len 62, info: &{Stream:0 SSN:2 Flags:0 _:0 PPID:1006632960 Context:0 TTL:0 TSN:2316183123 CumTSN:0 AssocID:40}
dump: 002e403a000004000a000000550002000000260016157e00572d10000000000000000000000000000000000079000f4002f839000004001002f839000001
Procedure Code: id-UplinkNASTransport (46)
PDU Length: 58
Protocol IEs: 4 items
  Item 0
    Protocol IE: id-AMF-UE-NGAP-ID (10)
      IE length: 0
  Item 1
    Protocol IE: id-RAN-UE-NGAP-ID (85)
      IE length: 2
        decoding id(85) not supported yet.
        dump: 0000
  Item 2
    Protocol IE: id-NAS-PDU (38)
      IE length: 22
        EPD: 5G Mobility Management (0x7e)
        Security Header: 0x0
        Message Type: Authentication Response (0x57)
  Item 3
[gnbsim]2021/01/01 11:26:39.546160 ngap.go:640: Unsupported Protocol IE: 121
    Protocol IE:  (121)
      IE length: 15
        decoding id(121) not supported yet.
        dump: 4002f839000004001002f839000001
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x53c739]

goroutine 1 [running]:
github.com/aead/cmac.NewWithTagSize(0x0, 0x0, 0x10, 0xa0e720, 0x8, 0x30, 0x0)
        /home/ubuntu/go/pkg/mod/github.com/aead/cmac@v0.0.0-20160719120800-7af84192f0b1/cmac.go:73 +0x29
github.com/aead/cmac.Sum(0xc000018450, 0x2b, 0x30, 0x0, 0x0, 0x10, 0xa0e720, 0x30, 0x1, 0xc000018420, ...)
        /home/ubuntu/go/pkg/mod/github.com/aead/cmac@v0.0.0-20160719120800-7af84192f0b1/cmac.go:46 +0x46
github.com/hhorai/gnbsim/encoding/nas.(*UE).ComputeMAC(0xc00014e038, 0xc000018300, 0xc000165f08, 0x1, 0x23, 0xc000018420)
        /home/ubuntu/go/pkg/mod/github.com/hhorai/gnbsim/encoding/nas@v0.0.0-20210101023828-c0503a75b825/nas.go:2137 +0x183
github.com/hhorai/gnbsim/encoding/nas.(*UE).enc5GSecurityProtectedMessageHeader(0xc00014e038, 0xc00001c904, 0xc000165f08, 0x8, 0x22, 0xc0000183f0)
        /home/ubuntu/go/pkg/mod/github.com/hhorai/gnbsim/encoding/nas@v0.0.0-20210101023828-c0503a75b825/nas.go:789 +0x15c
github.com/hhorai/gnbsim/encoding/nas.(*UE).MakeSecurityModeComplete(0xc00014e038, 0xc000018420, 0x23, 0x30)
        /home/ubuntu/go/pkg/mod/github.com/hhorai/gnbsim/encoding/nas@v0.0.0-20210101023828-c0503a75b825/nas.go:693 +0x192
main.(*testSession).registrateUE(0xc000109230)
        /home/ubuntu/gnbsim/example/example.go:179 +0x16b
main.main()
        /home/ubuntu/gnbsim/example/example.go:610 +0xdd

AMF logs
----------
ubuntu@free5g_304:~/free5gc-compose$ sudo docker logs amf
CommonConfig file: ../config/free5GC.conf
2021-01-01T11:06:00Z [INFO][AMF][App] amf
2021-01-01T11:06:00Z [INFO][AMF][App] AMF version:
        version: v3.0.4
        build time: 2020-12-31T15:06:38Z
        commit hash: 1b92f8cf
        commit time: 2020-09-28T21:02:22Z
        go version: go1.14.4 linux/amd64
2021-01-01T11:06:00Z [INFO][NAS][Message] set log level : info
2021-01-01T11:06:00Z [INFO][NAS][Message] set report call : true
2021-01-01T11:06:00Z [INFO][LIB][FSM] set log level : info
2021-01-01T11:06:00Z [INFO][LIB][FSM] set report call : true
2021-01-01T11:06:00Z [INFO][LIB][NGAP] set log level : info
2021-01-01T11:06:00Z [INFO][LIB][NGAP] set report call : true
2021-01-01T11:06:00Z [INFO][OAPI][NamfComm] set log level : info
2021-01-01T11:06:00Z [INFO][OAPI][NamfComm] set report call : true
2021-01-01T11:06:00Z [INFO][OAPI][NamfEvent] set log level : info
2021-01-01T11:06:00Z [INFO][OAPI][NamfEvent] set report call : true
2021-01-01T11:06:00Z [INFO][OAPI][NsmfPDUSess] set log level : info
2021-01-01T11:06:00Z [INFO][OAPI][NsmfPDUSess] set report call : true
2021-01-01T11:06:00Z [INFO][OAPI][NudrDataRepo] set log level : info
2021-01-01T11:06:00Z [INFO][OAPI][NudrDataRepo] set report call : true
2021-01-01T11:06:00Z [INFO][LIB][OAPI] set log level : info
2021-01-01T11:06:00Z [INFO][LIB][OAPI] set report call : true
2021-01-01T11:06:00Z [INFO][LIB][Aper] set log level : info
2021-01-01T11:06:00Z [INFO][LIB][Aper] set report call : true
2021-01-01T11:06:00Z [INFO][CommonTest][Comm] set log level : info
2021-01-01T11:06:00Z [INFO][CommonTest][Comm] set report call : true
2021-01-01T11:06:00Z [INFO][AMF][Init] Successfully initialize configuration ../config/amfcfg.conf
2021-01-01T11:06:00Z [INFO][AMF][Init] Log level is set to [info] level
2021-01-01T11:06:00Z [INFO][AMF][Init] Server started (/go/src/free5gc/src/amf/service/amf_init.go:115 free5gc/src/amf/service.(*AMF).Start)
2021-01-01T11:06:00Z [INFO][AMF][Util] amfconfig Info: Version[1.0.0] Description[AMF initial local configuration] (/go/src/free5gc/src/amf/util/init_context.go:18 free5gc/src/amf/util.InitAmfContext)
2021-01-01T11:06:00Z [INFO][AMF][NGAP] Listen on 10.100.200.12:38412 (/go/src/free5gc/src/amf/ngap/service/service.go:51 free5gc/src/amf/ngap/service.listenAndServe)
ubuntu@free5g_304:~/free5gc-compose$ sudo docker logs amf --follow
CommonConfig file: ../config/free5GC.conf
2021-01-01T11:06:00Z [INFO][AMF][App] amf
2021-01-01T11:06:00Z [INFO][AMF][App] AMF version:
        version: v3.0.4
        build time: 2020-12-31T15:06:38Z
        commit hash: 1b92f8cf
        commit time: 2020-09-28T21:02:22Z
        go version: go1.14.4 linux/amd64
2021-01-01T11:06:00Z [INFO][NAS][Message] set log level : info
2021-01-01T11:06:00Z [INFO][NAS][Message] set report call : true
2021-01-01T11:06:00Z [INFO][LIB][FSM] set log level : info
2021-01-01T11:06:00Z [INFO][LIB][FSM] set report call : true
2021-01-01T11:06:00Z [INFO][LIB][NGAP] set log level : info
2021-01-01T11:06:00Z [INFO][LIB][NGAP] set report call : true
2021-01-01T11:06:00Z [INFO][OAPI][NamfComm] set log level : info
2021-01-01T11:06:00Z [INFO][OAPI][NamfComm] set report call : true
2021-01-01T11:06:00Z [INFO][OAPI][NamfEvent] set log level : info
2021-01-01T11:06:00Z [INFO][OAPI][NamfEvent] set report call : true
2021-01-01T11:06:00Z [INFO][OAPI][NsmfPDUSess] set log level : info
2021-01-01T11:06:00Z [INFO][OAPI][NsmfPDUSess] set report call : true
2021-01-01T11:06:00Z [INFO][OAPI][NudrDataRepo] set log level : info
2021-01-01T11:06:00Z [INFO][OAPI][NudrDataRepo] set report call : true
2021-01-01T11:06:00Z [INFO][LIB][OAPI] set log level : info
2021-01-01T11:06:00Z [INFO][LIB][OAPI] set report call : true
2021-01-01T11:06:00Z [INFO][LIB][Aper] set log level : info
2021-01-01T11:06:00Z [INFO][LIB][Aper] set report call : true
2021-01-01T11:06:00Z [INFO][CommonTest][Comm] set log level : info
2021-01-01T11:06:00Z [INFO][CommonTest][Comm] set report call : true
2021-01-01T11:06:00Z [INFO][AMF][Init] Successfully initialize configuration ../config/amfcfg.conf
2021-01-01T11:06:00Z [INFO][AMF][Init] Log level is set to [info] level
2021-01-01T11:06:00Z [INFO][AMF][Init] Server started (/go/src/free5gc/src/amf/service/amf_init.go:115 free5gc/src/amf/service.(*AMF).Start)
2021-01-01T11:06:00Z [INFO][AMF][Util] amfconfig Info: Version[1.0.0] Description[AMF initial local configuration] (/go/src/free5gc/src/amf/util/init_context.go:18 free5gc/src/amf/util.InitAmfContext)
2021-01-01T11:06:00Z [INFO][AMF][NGAP] Listen on **10.100.200.12:38412** (/go/src/free5gc/src/amf/ngap/service/service.go:51 free5gc/src/amf/ngap/service.listenAndServe)

Please let me know if you need any other details.

**Comment by hhorai** [comment]
Please run your gnbsim with `/example -ip 10.100.200.12`.
`-ip` option was not specified in your log.

**Comment by namachis** [comment]
thank you so much for your quick response. It has worked.
