### ISSUE TITLE
panic: runtime error: index out of range [5] with length 5

### ISSUE THREAD

**Issue by regek** [hhorai/gnbsim#7]
Hi,

### After receiving a response from the AMF. it produces following error. 

```
[ngap]2020/08/19 16:21:36.564487 example.go:53: Dail LocalAddr: 127.0.0.1/172.17.0.1/192.168.37.134/10.100.200.1:38412; RemoteAddr: 10.100.200.12:38412
[ngap]2020/08/19 16:21:36.564525 example.go:58: SndBufSize: 212992, RcvBufSize: 212992
[ngap]2020/08/19 16:21:36.564779 example.go:77: write: len 44, info: &{Stream:0 SSN:0 Flags:0 _:0 PPID:1006632960 Context:0 TTL:0 TSN:0 CumTSN:0 AssocID:0}
[ngap]2020/08/19 16:21:36.566054 example.go:90: read: len 53, info: &{Stream:0 SSN:0 Flags:0 _:0 PPID:1006632960 Context:0 TTL:0 TSN:1006898554 CumTSN:0 AssocID:119}
dump: 20150031000004000100050100414d4600600008000002f839cafe0000564001ff005000100002f839000110080102031008112233
Procedure Code: id-NGSetup (21)
PDU Length: 49
Protocol IEs: 4 items
  Item 0
    Protocol IE: id-AMFName (1)
      IE length: 5
        decoding id(1) not supported yet.
        dump: 0100414d46
  Item 1
    Protocol IE: id-ServedGUAMIList (96)
      IE length: 8
        decoding id(96) not supported yet.
        dump: 000002f839cafe00
  Item 2
    Protocol IE: id-RelativeAMFCapacity (86)
      IE length: 1
        decoding id(86) not supported yet.
        dump: ff
  Item 3
    Protocol IE: id-PLMNSupportList (80)
      IE length: 16
        decoding id(80) not supported yet.
        dump: 0002f839000110080102031008112233

**panic: runtime error: index out of range [5] with length 5**

goroutine 1 [running]:
github.com/hhorai/gnbsim/encoding/nas.encSchemeOutput(0xc0000aede0, 0xf, 0x39802)
        /home/oai/go/pkg/mod/github.com/hhorai/gnbsim@v0.0.0-20200818125211-5907f815e1eb/encoding/nas/nas.go:1113 +0x7f
github.com/hhorai/gnbsim/encoding/nas.(*UE).enc5GSMobileIDTypeSUCI(0xc0000c6038, 0x0, 0xc0000e3dd8, 0x449f6e)
        /home/oai/go/pkg/mod/github.com/hhorai/gnbsim@v0.0.0-20200818125211-5907f815e1eb/encoding/nas/nas.go:1022 +0xb3
github.com/hhorai/gnbsim/encoding/nas.(*UE).enc5GSMobileID(0xc0000c6038, 0x0, 0x1, 0x0, 0x1, 0xc0000af610)
        /home/oai/go/pkg/mod/github.com/hhorai/gnbsim@v0.0.0-20200818125211-5907f815e1eb/encoding/nas/nas.go:986 +0x14e
github.com/hhorai/gnbsim/encoding/nas.(*UE).MakeRegistrationRequest(0xc0000c6038, 0xc0000a6a40, 0xc0000e3f18, 0x1)
        /home/oai/go/pkg/mod/github.com/hhorai/gnbsim@v0.0.0-20200818125211-5907f815e1eb/encoding/nas/nas.go:512 +0xe3
main.(*testSession).registrationRequest(0xc0000a6040)
        /home/oai/gnbsim/example/example.go:126 +0xc2
main.main()
        /home/oai/gnbsim/example/example.go:146 +0x8c

```

Thanks

**Comment by regek** [comment]
Solution

file nas.go
```
line 1003: schemeOutput           [5]uint8                ->         schemeOutput           [15]uint8

line 1111: func encSchemeOutput(msin string) (so [5]byte) ->         func encSchemeOutput(msin string) (so [15]byte)
```
